export const GET_DOGS = 'ALL_DOGS'
export const DOG_DETAIL="DOG_DETAIL"
export const FILTER_BY_CREATION = 'FILTER_BY_CREATION'
export const ORDER_BY_NAME = 'ORDER_BY_NAME'
export const ORDER_BY_WEIGHT = 'ORDER_BY_WEIGHT'
export const GET_BY_NAME = 'GET_BY_NAME'
export const GET_TEMPERAMENTS_LIST = 'GET_TEMPERAMENTS_LIST'
export const FILTER_BY_TEMPER = 'FILTER_BY_TEMPER'